NUMPY

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
n=np.array(mylist)
n

array([1, 2, 3])

In [4]:
type(mylist)

list

In [5]:
type(n)

numpy.ndarray

In [6]:
n = np.array([1,2,3])
n

array([1, 2, 3])

CREATING MULTI DIMENTIONAL ARRAY

In [7]:
list_of_list = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(list_of_list)

numpy.ndarray

In [9]:
list_of_list.shape

(3, 3)

ARANGE FUNCTION 

In [10]:
# return evenly spaced values within a given interval

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


NUMPY ZEROS ONES EYE

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
m=np.arange(50)

In [21]:
len(m)

50

RESHAPE FUNCTION 

In [22]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
m.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

LINSPACE

In [24]:
o=np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [25]:
len(o)

10

RESIZE FUNCTION 

In [26]:
o.resize(5,2) # will change the original one ...
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [27]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

RANDOM.RAND

In [28]:
# random numbers between 0 and 1 
np.random.rand(3,2)

array([[0.81612605, 0.1196627 ],
       [0.004346  , 0.54266508],
       [0.37808403, 0.77990828]])

RANDOM.RANDN

In [29]:
# return vlaues from standard normal distribution 
np.random.randn(3,3)

array([[ 0.22962053,  0.63906317,  0.20115897],
       [-0.23327114,  0.67585174,  0.69951429],
       [-0.26382165, -2.00156091,  1.24675866]])

RANDOM.RANDINT

In [30]:
# gives integer from low(inclusion) to high (exclusion) with number of random numbers
m=np.random.randint(4,15,10)

In [31]:
len(m)

10

In [32]:
m.reshape(5,2)

array([[13,  7],
       [ 9, 10],
       [ 5,  9],
       [10, 14],
       [10,  5]])

In [33]:
tt = np.random.randint(0,10,(4,3))
tt

array([[1, 5, 3],
       [8, 4, 1],
       [8, 3, 2],
       [4, 9, 5]])

INDEXING AND SLICING 

In [34]:
m = np.random.randint(4,15,10)
m

array([ 4,  8,  9, 10, 14, 12, 13,  6,  5, 13])

In [35]:
m[1]

8

In [36]:
m[-1]

13

In [37]:
m[3:7]

array([10, 14, 12, 13])

In [38]:
m[3:]

array([10, 14, 12, 13,  6,  5, 13])

In [39]:
m[5:-2]

array([12, 13,  6])

In [40]:
m.resize(2,5)

In [42]:
m = np.arange(64)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [46]:
m.resize(8,8)
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [45]:
m[2,3]

19

In [47]:
m[4,2:5]

array([34, 35, 36])

In [48]:
m[2:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [49]:
m[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [50]:
m[m>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63])

In [51]:
m>25

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

BROADCASTING 

In [52]:
m[m>25] = 25 # casting all the values that are grater than 25 to 25

In [53]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

CREATE A COPY DATASET

In [55]:
m1 = m[3:,3:]
m1

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [57]:
m_copy = m.copy()
m_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

 DATA FRAME

In [60]:
import pandas as pd

In [ ]:
data = pd.read_csv('Olympic.csv',skiprows=True)
data.head() # see first 5 rows 

df = data.copy()
df.head()
df['Country']

In [61]:
df[['award','award1']] = df[['Unnamed:4','Unamed:5']]
df.head()
d1.drop(['Unnamed:5','Unnamed:4'],axis=1) # drop in column 
df.head()

NameError: ignored

ASSIGNMENT 

In [62]:
import numpy as np

In [63]:
array1 = np.arange(15,40)

In [64]:
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [65]:
array2  = np.arange(10,26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [66]:
even_array1 = np.arange(2,20,2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
even_array2 = np.arange(34,42,2)
even_array2

array([34, 36, 38, 40])

In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.stack((a,b),axis = 0)
print(c)

[[1 2 3]
 [4 5 6]]


In [75]:
mat = np.arange(0,36)
mat.resize(6,6)
mat

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [77]:
mat[2][1]

13

In [78]:
x = np.random.randn(5,2)
x

array([[ 0.56387975, -0.43695158],
       [-0.95058864,  0.1978272 ],
       [ 0.53230354,  1.11089455],
       [ 0.43522898, -0.36873896],
       [ 1.5729897 ,  0.60406301]])

In [81]:
x[4,1]

0.6040630141626683

In [83]:
np.min(x)

-0.9505886387287886

In [84]:
np.max(x)

1.5729896983768747

In [85]:
np.std(x)

0.7120607254192696

In [86]:
np.var(x)

0.5070304766846164

In [87]:
np.mean(x)

0.32609075468821136